enum boardMutations {
    SELECT_PIECE = 'SELECT_PIECE',
    UNSELECT_ALL_PIECES = 'UNSELECT_ALL_PIECES',
    MOVE_PIECE = 'MOVE_PIECE',
    SHOW_POSSIBLE_MOVES = 'SHOW_POSSIBLE_MOVES',
    HIDE_POSSIBLE_DESTINATIONS = 'HIDE_POSSIBLE_DESTINATIONS',
    MARK_AS_POSSIBLE_DESTINATION = 'MARK_AS_POSSIBLE_DESTINATION',
    HIDE_POSSIBLE_KILLS = 'HIDE_POSSIBLE_KILLS',
    MARK_AS_POSSIBLE_KILL = 'MARK_AS_POSSIBLE_KILL',
    REMOVE_PIECE_FROM = 'REMOVE_PIECE_FROM',
    ADD_PIECE = 'ADD_PIECE',
    TOGGLE_PLAYER = 'TOGGLE_PLAYER',
    INCREMENT_ROUND = 'INCREMENT_ROUND',
    ADD_MOVE = 'ADD_MOVE',
    SET_PLAYER_COLOR = 'SET_PLAYER_COLOR',
    RESET_GAME = 'RESET_GAME',
}

export default boardMutations;
